name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make compile
      run: make compile
    - name: Github Release
      uses: elgohr/Github-Release-Action@v3.1
      with:
        # The name of the release to publish
        release: 
